
#DB_USER:  root
#DB_PASSWORD:  root
#DB_NAME: mr_cherry
#MP_TOKEN: access_token_mercado_pago

spring:
  application:
    name: Mr. Cherry
  datasource:
    url: jdbc:mysql://localhost:3306/mr_cherry?ServerTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect



server:
  port: 8080